name: flash_chat
description: "Incorporate Firebase NoSQL and secure authentication method into Flutter apps"

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.2.1
  firebase_core: ^1.10.0
  firebase_auth: ^3.3.5
  cloud_firestore: ^3.1.5
  modal_progress_hud_nsn: ^0.5.1
  firebase_core_platform_interface: 4.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - images/